# Generated by Django 4.2.8 on 2023-12-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('table_num_seats', models.IntegerField(choices=[(4, '2'), (4, '4'), (6, '6')], default=2)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
